language: java
services:
- docker
env:
  global:
  - IMAGE=gcr.io/exam1pg301/exam1image
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: d5+dGPOq2igGOcft9f0IkxCXtAL3KJDsrgRVnYUDTY97MeXU9psLr2LVQBXZjbZ4e7t1fz5nS/AzscdMgrBJdmxKzLUsQloshTJHpG6XSr8wBq/4wWfNhe3K1H1i8/As1lqEU8SrPpB/kRVB6BrLKnZ9F+14ik6ekvZGOefS+aXaJREvHf3RXTGZk/P5lyRAlB8W6CeSUMkVtVP5lBEh4qzJEbsqbOYwFx8R7bXpMlqfSH820lym+vcs2OJ1uOIbln5N5LxglcZX9v4PD65WHla+rRABCHwOvYE923bnrgd3RfxqZ3s3K/LpEAcuOfQ8mAuFteoNr2CfnL79pJ4HSEiCQmmOIzs/F+qRxWMqSPOVUbhFhEhxroE4frwphO7L7iHvMdzju0F5FfhsMYNsOi7nkfHrcUsCOFjzkPaOlyFjKgt4N0BBTltjBu0DnUpvHf6bKVRccllhj59tVxJ/RTHmGkfpFgRRuwha965IeH1hssPvvDAKDi2rXOeJvI9Rs/Ep44fH+amjv4zmE8il5Th9DUMAF6wVL3KNqT6MbgSY4ji5HOoB+a91sqg+WAYS+K+0vIvkVIuYUaQIgxbftAGZK6xzADIpCp2/Q9fNcQYDjGaaJZoOV1q4B0iKLy0IGPUkmXG6dqZtIVUE8rj0QXVkLWrxaRAtFL4tl0jDces=
  - secure: BQGnaZOMf8hk0AnGZNiMRxKJI071C9T4p3kT4vYtzxsV5xo6Fzrs88zAG22uokP7bye2tIEBTW23kpRyLRNBf4Qi8E6mgX50Ft86gZ7shFdKd4fg6ELMOTXhwRUgdxRCNZa0v+ma+oRmCfzl1d98QzFBmRLnjcLnj9Mk3ioc3XPpXE5qP2rNBxknp4NHV0uU6LFVBp2rNxSR6wlJKR+X4zrl5N/cl7kQjZlre7XVqLMsZC8cBO2E3oqQ1e2g87orq4ecEg4UDeM3r9fnfZwpOoJstp5umpsPjG0dm9e1hdb9ME1pWMuFnJap/NnzVZ9WG/4QHdG4USkw4sagpFqWVGnILPQ8YLYj9ZqOV6BlRn4fJhoBg5z3T7Qtzg6D3m3E04miUYjzMzJbqE6077ew+x+gD8x1uUfxUVW78D2DLKvj50vwuna+fZ5k9ny/sTppLPEEs6dhgCMRmie/bFqjodmtMcpPuPP23u8ALmcCa5LpyK9jPmqKnfd3uu7RhnbJNvCR06H37o2Q0Z+rH+fErz3prZKFQw063X2SU33uDnOdFxIV5vzncq/Szz/IFwhjiGQBs+4Ju6mp+86POKZtIiISFoIHsj1OxsMQmtw7veYz7AlQzq3DPyS3z9EKnW5zZYhRZqPYR02sAZow5ba2IlJdxws6n5iIBiu9y4OxzeA=
  - secure: DnlFX38UB4YGnSKfPUG+6ydRox+1CM+FdKXz3fK0GiX/cbAIxvmNRcV2T89/dFSNZnaqwuKP0D8nzSb2GdME/GBf5mkuwZ/S+dmZWMNdDnYxuH8P/pLCXKcl+BltbvhfrLlMsDdsgmEtxsNq0ztMMj6jPSk/Duah+fcqo6vyFNUzP7pLBI4Q01+XP6+BnIIlUAF4YdTxYZ3qKqJy+FOfsiYb39kUdnOLWqYjhlJLeodAU5sGfebj1ePT3Y2uHoiTMPGBupObiaI0gHu7voeiCoJmVadWuNWtD1X6i9wPCe0zQyMLwy1qXWWMQ9KmcvGAAsAYbFxSgVeuZ9vGq2n++icuKNgfXaelf3/srnKLIPvwL+GTj17fhLqV0zvXVZYNTI1LJcOgPDYATyUx9dAj75QhSrygFiB2z6zwnSMs3wWCLFHlOBWIgZQ8fRC2Sye8lIGXJ3N4fxU0eyewCCCQCaRKTqN0q94mFsjnl1bQqPY7rrddoNApPdrTqmJRMo6Sq6XqawsNOZqANQ4by9t+aabB2xj8DD0VJkpLr2sAINeySFEJ62tQOTHXOPremRdo1MaVuG20sFwLcRaKVQ3DYh/+/QPQFfKg+KdNa4fBGjCiVai60E7qQDw26Wf7+mdKq+NXK4IY7uMRBN96GdxJO7OgOe4iSljT0+Xi0vZAtSM=
before_install:
- openssl aes-256-cbc -K $encrypted_9bc4bf243818_key -iv $encrypted_9bc4bf243818_iv
  -in exam1pg301-3e8c21e61719.json.enc -out exam1pg301-3e8c21e61719.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=exam1pg301-3e8c21e61719.json
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta
install: true
script:
- |-
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  set +x
