language: java
services:
- docker
env:
  global:
  - IMAGE=gcr.io/terraform-292215/exam1image-10013
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: s2pxYLaFIsk5NrCCAXFwx9EkzEOee98zm/j1a4NcDG/KNGe61v8bFrDl5xCLrEJpSeTbECh6pCjLQStJ5g1PBHV+8vGF2sbJtjZfThko2aFgNHk6PRyIFFRM+d7lT035NteR59cRfayhvod2bC5JvNCsmY4zsEpTGv8flHgRHE1C7ozAtQKbnzzebvbY/1hdFt5X/nW8AZ1/wHc/YajnMg5sUnUn/3kBxsD6icLkK1V9h4pA/s6tc/HD4ra4ofVslRP24k82B1sMHCn3dgeN0QrjrJC1GWQ+xrSq158RioOBZRqqHXqbU2lZf6VknztFrPfTjiJ21XadQAVFRpfxHCS+9P8oArV/9NZmkMFDhEuoRH4UbyBuMyUc04e9JmBi33yqMBKk8Mi6gc16NFBm+7SJ513Hbr16x0Z7JX7OWAmRly+2fsCdx5nN9LDvITPXkzgOE6s/hDKVWXLaO87l9+oPjQwvAYuEOwXS/LR0Falsqjkz711O6UbLBKEDYUYNTxXXyCUvEqsg2p2mTEAjRv1tGd99PLca9BLnViZ8Hz96ZwxtP8gZnmr039ZjrR6tlNLsMxCO8o9etWHmQCpbUe8vGbCf5Wop2CNGq/YmTYSqzjMf3rCO2Iwut4Hj6U8FajKjtIIrdFk8JCEoHZkJZP9QpX6dzKY2eZHALH7d5N0=
  - secure: dFA6h2sfyWUo5puZrmjOeDaBa2w+ZTTBB3OmGQxfZ7KqK9uPBW6LvUkdvlWWjdgfIOIxUL9bNXT63/QERfSzqyBq4dByL2FvhudLhKRJ+QRWUeSlX9PppQPSdUT2C/7DKPPEX6H09OFjDSinUMo0pwNgDaqYQHUSNC3NCIS9KZwp/gO2BUcthmENAaRKJYpjIq/b1ejhJeZQDu/9pZPD0bWX0qkarV/nqX4CliHFkP2TDJg+s0u4gt5KOTKyPAB5liG6tLcIOR2NbnL1ZbeeeF2vRLHLcoZt5xTW1GghexcMrFrvmpZ/OnGeVTueINawrp6NPi2DOy+FMSODBCCGpzSpksZuIViws9p7UpbEPiYo8cZbq5q7AIT2ABU6gccch2HsBj9Q8kshaZJBTTD1/KFVeDu3XdzU3NJm1zlg2Dhq+KkHdIe/Us63pBdvNQ2qKq1AsD9kuk0oIBXEYy47gBlw7SvOXmFwhwB9Ub8jIYiLfHgf2giz0QWXyQfurLDWk0O31FKPNKexz9U7fUewlYdg55+QEfxeks8lMBix1sxlsw0CH+u0Z+219DL55Up9NGGAQkqpihFL08VtfWmigPGQzf/ioCQ3OHgMqq0CJYpZemLgngM7nDjUrokJeqK7/S4nyUjCgRpe4jE7c6jYqc1A55jFJplpiHjuL+X/yz8=
before_install:
- openssl aes-256-cbc -K $encrypted_06803aa82a44_key -iv $encrypted_06803aa82a44_iv
  -in exam1pg301.json.enc -out exam1pg301.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=exam1pg301.json
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta
install: true
script:
- |-
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  set +x
