language: java
services:
- docker
env:
  global:
  - IMAGE=gcr.io/exam1pg301/exam1image
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  #  - GCP_PROJECT_ID
  - secure: d5+dGPOq2igGOcft9f0IkxCXtAL3KJDsrgRVnYUDTY97MeXU9psLr2LVQBXZjbZ4e7t1fz5nS/AzscdMgrBJdmxKzLUsQloshTJHpG6XSr8wBq/4wWfNhe3K1H1i8/As1lqEU8SrPpB/kRVB6BrLKnZ9F+14ik6ekvZGOefS+aXaJREvHf3RXTGZk/P5lyRAlB8W6CeSUMkVtVP5lBEh4qzJEbsqbOYwFx8R7bXpMlqfSH820lym+vcs2OJ1uOIbln5N5LxglcZX9v4PD65WHla+rRABCHwOvYE923bnrgd3RfxqZ3s3K/LpEAcuOfQ8mAuFteoNr2CfnL79pJ4HSEiCQmmOIzs/F+qRxWMqSPOVUbhFhEhxroE4frwphO7L7iHvMdzju0F5FfhsMYNsOi7nkfHrcUsCOFjzkPaOlyFjKgt4N0BBTltjBu0DnUpvHf6bKVRccllhj59tVxJ/RTHmGkfpFgRRuwha965IeH1hssPvvDAKDi2rXOeJvI9Rs/Ep44fH+amjv4zmE8il5Th9DUMAF6wVL3KNqT6MbgSY4ji5HOoB+a91sqg+WAYS+K+0vIvkVIuYUaQIgxbftAGZK6xzADIpCp2/Q9fNcQYDjGaaJZoOV1q4B0iKLy0IGPUkmXG6dqZtIVUE8rj0QXVkLWrxaRAtFL4tl0jDces=
before_install:
- openssl aes-256-cbc -K $encrypted_9bc4bf243818_key -iv $encrypted_9bc4bf243818_iv
  -in exam1pg301-3e8c21e61719.json.enc -out exam1pg301-3e8c21e61719.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=exam1pg301-3e8c21e61719.json
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta
install: true
script:
- |-
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  set +x
